name: Run Unit Test Job

# TODO:
# - Implement Functional Tests using TTK as an example

on:
  workflow_call: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: |
          echo "To Be Done"

